spring:
   profiles:
       active: dev
   datasource:
       url: jdbc:mysql://localhost/freelancertech_base
       username: freelancertech
       password: freelancertech
       driverClassName: com.mysql.jdbc.Driver
   jpa:
     database: MYSQL
     show-sql: true
     hibernate:
         ddl-auto: none
     properties:
         hibernate:
             dialect: org.hibernate.dialect.MySQL5Dialect
             format_sql: true
   thymeleaf:
       cache: false

       
  
   

       